version: "3.7"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafak-net

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - d:/dotnet-test/kafkaTest:/var/run/docker.sock
    networks:
      - kafak-net
  
  client:
    image: client:dev
    build:
      context: .
    restart: always
    depends_on:
      - kafka
    networks:
      - kafak-net

networks:
  kafak-net:
    driver: bridge