version: "3.7"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"    

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "testtopic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: "9092"
    volumes:
      - /dotnet-test/KafkaVolume:/var/run/docker.sock

